# Generated by Django 3.2.4 on 2022-05-02 10:44

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Порядок показа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Описание')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='URL генерируется автоматически из названия раздела, но может быть задан вручную', unique=True, verbose_name='URL')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Порядок показа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('keywords', models.CharField(blank=True, max_length=1000, verbose_name='Ключевые слова')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Описание')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='URL генерируется автоматически из названия раздела, но может быть задан вручную', unique=True, verbose_name='URL')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('main_photo_xxl2', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', help_text='Формат файла: jpg, jpeg или png. Ограничение размера: 3 Мбайт.', keep_meta=True, quality=80, size=[2400, 1800], upload_to=shop.models.get_file_path, verbose_name='Основное изображение')),
                ('bottom_photo_xxl2', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', help_text='Формат файла: jpg, jpeg или png. Ограничение размера: 3 Мбайт.', keep_meta=True, quality=80, size=[2400, 1800], upload_to=shop.models.get_file_path, verbose_name='Картинка для нижнего блока')),
            ],
            options={
                'verbose_name': 'материал',
                'verbose_name_plural': 'Товары',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Порядок показа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Описание')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='URL генерируется автоматически из названия раздела, но может быть задан вручную', unique=True, verbose_name='URL')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='item_basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=500, verbose_name='Ключ сессии')),
                ('amount', models.IntegerField(null=True, verbose_name='Количество')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.item')),
            ],
            options={
                'verbose_name': 'материал',
                'verbose_name_plural': 'Список заказов',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.subcategory', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная')),
                ('name', models.CharField(max_length=500, verbose_name='Название скидки')),
                ('type', models.CharField(blank=True, choices=[('1', 'Процент'), ('2', 'Валюта')], max_length=100, verbose_name='Тип')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Величина скидки')),
                ('starts', models.DateTimeField(blank=True, null=True, verbose_name='Начало действия')),
                ('ends', models.DateTimeField(blank=True, null=True, verbose_name='Окончание действия')),
                ('item', models.ManyToManyField(blank=True, to='shop.item', verbose_name='Товары')),
                ('subcategory', models.ManyToManyField(blank=True, to='shop.subcategory', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'материал',
                'verbose_name_plural': 'Скидки',
            },
        ),
        migrations.CreateModel(
            name='coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная')),
                ('name', models.CharField(max_length=500, verbose_name='Название купона')),
                ('number', models.CharField(blank=True, max_length=500, verbose_name='Номер купона (генерируется автоматически)')),
                ('usage', models.CharField(blank=True, choices=[('1', 'Одноразовый'), ('2', 'Многоразовый')], max_length=100, verbose_name='Возможность использования')),
                ('type', models.CharField(blank=True, choices=[('1', 'Процент'), ('2', 'Валюта')], max_length=100, verbose_name='Тип')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Величина купона')),
                ('starts', models.DateTimeField(blank=True, null=True, verbose_name='Начало действия')),
                ('ends', models.DateTimeField(blank=True, null=True, verbose_name='Окончание действия')),
                ('used', models.BooleanField(blank=True, default=False, verbose_name='Использован')),
                ('item', models.ManyToManyField(blank=True, to='shop.item', verbose_name='Товары')),
                ('subcategory', models.ManyToManyField(blank=True, to='shop.subcategory', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'материал',
                'verbose_name_plural': 'Купоны',
            },
        ),
    ]
