# Generated by Django 3.2.4 on 2022-05-02 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='keywords',
        ),
    ]
