# Generated by Django 3.2.4 on 2022-05-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_item_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_rub',
            field=models.IntegerField(null=True),
        ),
    ]
