# Generated by Django 3.2.4 on 2022-05-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_item_price_rub'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={},
        ),
        migrations.AlterModelOptions(
            name='item_basket',
            options={},
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='ends',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='item',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='name',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='number',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='starts',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='type',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='usage',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='used',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='ends',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='item',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='name',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='starts',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='type',
        ),
        migrations.RemoveField(
            model_name='item_basket',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='item_basket',
            name='item',
        ),
        migrations.RemoveField(
            model_name='item_basket',
            name='session_key',
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
