# Generated by Django 3.2.4 on 2022-05-03 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20220503_0657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='price_rub',
            new_name='price',
        ),
    ]
