# Generated by Django 3.2.4 on 2022-05-03 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20220503_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='bottom_photo_xxl2',
        ),
    ]
