# Generated by Django 3.2.4 on 2022-05-12 12:00

from django.db import migrations
import django_resized.forms
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_item_bottom_photo_xxl2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='main_photo_xxl2',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', help_text='Формат файла: jpg, jpeg или png. Ограничение размера: 3 Мбайт.', keep_meta=True, quality=80, size=[1920, 1080], upload_to=shop.models.get_file_path, verbose_name='Основное изображение'),
        ),
    ]
