# Generated by Django 3.2.4 on 2022-05-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_item_main_photo_xxl2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True, verbose_name='URL'),
        ),
    ]
