# Generated by Django 3.2.4 on 2021-12-13 17:19

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_item_photos_main_photo_xxl2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
        migrations.AddField(
            model_name='item',
            name='URL',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='URL генерируется автоматически из названия раздела, но может быть задан вручную', unique=True, verbose_name=shop.models.category),
        ),
    ]
