# Generated by Django 3.2.4 on 2021-12-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20211213_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='URL',
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='URL генерируется автоматически из названия раздела, но может быть задан вручную', unique=True, verbose_name='URL'),
        ),
    ]
