# Generated by Django 3.2.4 on 2021-12-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20211213_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='css',
            field=models.CharField(default='-', max_length=50, null=True, verbose_name='CSS класс'),
        ),
    ]
