# Generated by Django 3.2.4 on 2021-12-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_category_css'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='css',
        ),
        migrations.AlterField(
            model_name='item',
            name='price_eur',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена в евро'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_rub',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена в рублях'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_usd',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена в долларах'),
        ),
    ]
