# Generated by Django 3.2.4 on 2021-12-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20211215_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price_eur',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена в евро'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_rub',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена в рублях'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_usd',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена в долларах'),
        ),
    ]
