# Generated by Django 3.2.4 on 2022-05-03 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaleCode',
        ),
    ]
