# Generated by Django 3.2.4 on 2022-05-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_rename_salecode_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(),
        ),
    ]
